### ISSUE TITLE
VERY BAD ISSUE

### ISSUE THREAD

**Issue by tomcek112** [benjaminwilson/VIP-very-important-project#1]
SOMETHING is WRONG! Has to get fixed ASAP!!!!!!

**Comment by benjaminwilson** [comment]
@tomcek112 yes you're right, but dont have time to check it.

**Comment by tomcek112** [comment]
aisdfgwiquf
@potogold add 5000

**Comment by tomcek112** [comment]
ashgdashdfasd

**Comment by tomcek112** [comment]
@potogold add 5000

**Comment by potogold** [comment]
@tomcek112 I don't understand

**Comment by tomcek112** [comment]
@potogold add 5000$

**Comment by potogold** [comment]
@tomcek112 I don't understand

**Comment by tomcek112** [comment]
@potogold add $5000

**Comment by potogold** [comment]
@tomcek112 offers $5000.00

**Comment by tomcek112** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@tomcek112 released funds to @netbe

**Comment by tomcek112** [comment]
@potogold add $3000

**Comment by potogold** [comment]
@tomcek112 offers $3000.00

**Comment by tomcek112** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@tomcek112 released funds to @netbe

**Comment by benjaminwilson** [comment]
@potogold add $300

**Comment by potogold** [comment]
@tomcek112 offers $3000.00

**Comment by potogold** [comment]
@tomcek112 offers $3000.00

**Comment by potogold** [comment]
@tomcek112 released funds to @netbe

**Comment by potogold** [comment]
@benjaminwilson offers $300.00

**Comment by netbe** [comment]
@benjaminwilson I guess you ran the bot, should deactivate the twilio though
