### ISSUE TITLE
ACTUALLY REALLY BAD ISSUE

### ISSUE THREAD

**Issue by tomcek112** [benjaminwilson/VIP-very-important-project#8]
SO BAD THIS JUST LOST ME $500 MILLION!!!!

**Comment by tomcek112** [comment]
@potogold add $300

**Comment by potogold** [comment]
@tomcek112 offers $300.00

**Comment by tomcek112** [comment]
@potogold reward @netbe

**Comment by potogold** [comment]
@tomcek112 released funds to @netbe

**Comment by tomcek112** [comment]
@potogold hello

**Comment by potogold** [comment]
@tomcek112 I don't understand
